export const runtime = "edge";

import { Redis } from "@upstash/redis";

const redis = Redis.fromEnv();
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? "00000";
const CORS = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Methods": "GET, POST, PATCH, DELETE, OPTIONS", "Access-Control-Allow-Headers": "Content-Type", "Content-Type": "application/json" };

function json(data, status = 200) { return new Response(JSON.stringify(data), { status, headers: CORS }); }
async function getJson(key, def) { try { const d = await redis.get(key); return d ?? def; } catch { return def; } }
async function setJson(key, data) { await redis.set(key, JSON.stringify(data)); }

export default async function handler(req) {
  const url = new URL(req.url);
  const method = req.method;
  if (method === "OPTIONS") return new Response("", { status: 200, headers: CORS });
  const path = url.pathname.replace(/^\/?api/, "") || "/";
  let body = {};
  if (method !== "GET" && method !== "HEAD") { try { body = await req.json(); } catch {} }
  const q = Object.fromEntries(url.searchParams.entries());
  try {
    if (path === "/healthz") return json({ status: "ok" });
    if (path === "/bblm" && method === "GET") return json(await getJson("bblm", { hasData: false, gradeNames: [], products: [], totalProducts: 0, updatedAt: null, updatedBy: "", sourceLabel: "" }));
    if (path === "/bblm" && method === "POST") { const { gradeNames, products, sourceLabel, updatedBy } = body; if (!Array.isArray(products)) return json({ success: false, message: "products must be an array" }, 400); await setJson("bblm", { hasData: true, gradeNames: Array.isArray(gradeNames) ? gradeNames : [], products, totalProducts: products.length, updatedAt: new Date().toISOString(), updatedBy: updatedBy ?? "unknown", sourceLabel: sourceLabel ?? "unknown" }); return json({ success: true, totalProducts: products.length }); }
    if (path === "/bblm-status" && method === "GET") return json(await getJson("bblm-status", { status: "updating", updatedAt: null }));
    if (path === "/bblm-status" && method === "POST") { const { status, adminPassword } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); if (status !== "updated" && status !== "updating") return json({ success: false, message: "invalid status" }, 400); const updatedAt = new Date().toISOString(); await setJson("bblm-status", { status, updatedAt }); return json({ success: true, status, updatedAt }); }
    if (path === "/pwd-status" && method === "GET") return json(await getJson("pwd-status", {}));
    if (path === "/pwd-status" && method === "POST") { const { username, changedAt } = body; if (!username) return json({ success: false, message: "username required" }, 400); const cur = await getJson("pwd-status", {}); cur[username] = changedAt ?? new Date().toISOString(); await setJson("pwd-status", cur); return json({ success: true }); }
    if (path === "/activity-log" && method === "GET") { if (q.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); let logs = await getJson("activity-logs", []); if (q.username) logs = logs.filter(l => l.username === q.username); return json({ success: true, logs: logs.slice(0, Math.min(parseInt(q.limit ?? "100") || 100, 1000)) }); }
    if (path === "/activity-log" && method === "DELETE") { if (body.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); await setJson("activity-logs", []); return json({ success: true }); }
    if (path === "/activity-log" && method === "POST") { const { username, action, detail } = body; if (!username || !action) return json({ success: false, message: "username and action required" }, 400); const logs = await getJson("activity-logs", []); logs.unshift({ username, action, detail: detail ?? "", createdAt: new Date().toISOString() }); if (logs.length > 1000) logs.length = 1000; await setJson("activity-logs", logs); return json({ success: true }); }
    if (path === "/login" && method === "POST") { const { username, password } = body; if (!username || !password) return json({ success: false, message: "username dan password wajib" }, 400); const users = await getJson("users", []); const user = users.find(u => u.username === username.trim() && u.password === password.trim()); if (!user) return json({ success: false, notFound: true, message: "User tidak ditemukan" }, 404); if (user.suspended) return json({ success: false, suspended: true, message: "Akun ditangguhkan" }, 403); return json({ success: true, namaLengkap: user.namaLengkap || user.username }); }
    if (path === "/users" && method === "GET") { if (q.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const users = await getJson("users", []); return json({ success: true, users: users.map(u => ({ username: u.username, namaLengkap: u.namaLengkap || u.username, suspended: u.suspended ?? false, createdAt: u.createdAt ?? null })) }); }
    if (path === "/users" && method === "POST") { const { adminPassword, username, password, namaLengkap } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); if (!username || !password) return json({ success: false, message: "username dan password wajib" }, 400); const users = await getJson("users", []); if (users.find(u => u.username === username.trim())) return json({ success: false, message: "Username sudah ada" }, 409); users.push({ username: username.trim(), password: password.trim(), namaLengkap: (namaLengkap || username).trim(), suspended: false, createdAt: new Date().toISOString() }); await setJson("users", users); return json({ success: true }); }
    if (path === "/users/import" && method === "POST") { const { adminPassword, usersData } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); if (!Array.isArray(usersData)) return json({ success: false, message: "usersData must be array" }, 400); const existing = await getJson("users", []); const map = {}; existing.forEach(u => { map[u.username] = true; }); let added = 0; usersData.forEach(u => { if (u.username && u.password && !map[u.username]) { existing.push({ username: u.username, password: u.password, namaLengkap: u.namaLengkap || u.username, suspended: false, createdAt: new Date().toISOString() }); map[u.username] = true; added++; } }); await setJson("users", existing); return json({ success: true, added, total: existing.length }); }
    const uPatch = path.match(/^\/users\/([^/]+)$/);
    if (uPatch && method === "PATCH") { const { adminPassword, namaLengkap, suspended, password } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const username = decodeURIComponent(uPatch[1]); const users = await getJson("users", []); const idx = users.findIndex(u => u.username === username); if (idx === -1) return json({ success: false, message: "User tidak ditemukan" }, 404); if (namaLengkap !== undefined) users[idx].namaLengkap = namaLengkap.trim(); if (suspended !== undefined) users[idx].suspended = suspended; if (password) users[idx].password = password.trim(); await setJson("users", users); return json({ success: true }); }
    const uDel = path.match(/^\/users\/([^/]+)$/);
    if (uDel && method === "DELETE") { const { adminPassword } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const username = decodeURIComponent(uDel[1]); let users = await getJson("users", []); const before = users.length; users = users.filter(u => u.username !== username); if (users.length === before) return json({ success: false, message: "User tidak ditemukan" }, 404); await setJson("users", users); return json({ success: true }); }
    if (path === "/maintenance" && method === "GET") return json(await getJson("maintenance", { active: false, message: "", updatedAt: null }));
    if (path === "/maintenance" && method === "POST") { const { adminPassword, active, message } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const data = { active: !!active, message: message ?? "", updatedAt: new Date().toISOString() }; await setJson("maintenance", data); return json({ success: true, ...data }); }
    if (path === "/backup" && method === "GET") { if (q.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const [users, bblm, logs, requests, maintenance, bblmStatus] = await Promise.all([getJson("users",[]),getJson("bblm",{}),getJson("activity-logs",[]),getJson("product-requests",[]),getJson("maintenance",{}),getJson("bblm-status",{})]); return json({ success: true, exportedAt: new Date().toISOString(), data: { users, bblm, "activity-logs": logs, "product-requests": requests, maintenance, "bblm-status": bblmStatus } }); }
    if (path === "/restore" && method === "POST") { const { adminPassword, data } = body; if (adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); if (!data) return json({ success: false, message: "data required" }, 400); let restored = 0; await Promise.all(["users","bblm","activity-logs","product-requests","maintenance","bblm-status"].map(async k => { if (data[k] !== undefined) { await setJson(k, data[k]); restored++; } })); return json({ success: true, message: restored + " kunci direstore" }); }
    if (path.startsWith("/price-history/") && method === "GET") { const barcode = decodeURIComponent(path.replace("/price-history/","")); const [ind, prev] = await Promise.all([getJson(`price-history:${barcode}`,null),getJson("price-snapshot-prev",{date:null,prices:{}})]); const pp = prev.prices?.[barcode]; return json({ success: true, data: pp != null ? { price: pp, date: prev.date } : ind }); }
    if (path === "/price-history" && method === "POST") { const { barcode, price } = body; if (!barcode || price === undefined) return json({ success: false, message: "barcode dan price wajib" }, 400); const today = new Date().toISOString().slice(0,10); const ex = await getJson(`price-history:${barcode}`,null); if (!ex || ex.date !== today) await setJson(`price-history:${barcode}`, { price: Number(price), date: today }); return json({ success: true }); }
    if (path === "/sync-prices" && method === "GET") { const [cur, prev] = await Promise.all([getJson("price-snapshot-current",{date:null,prices:{}}),getJson("price-snapshot-prev",{date:null,prices:{}})]); return json({ success: true, current: { date: cur.date, count: Object.keys(cur.prices||{}).length }, prev: { date: prev.date, count: Object.keys(prev.prices||{}).length, prices: prev.prices||{} } }); }
    if (path === "/sync-prices" && method === "POST") { const { items, forceOverwrite } = body; if (!Array.isArray(items)||!items.length) return json({ success: false, message: "items harus array" }, 400); const today = new Date().toISOString().slice(0,10); const cur = await getJson("price-snapshot-current",{date:null,prices:{}}); if (cur.date===today&&!forceOverwrite) return json({ success: true, saved: 0, message: "sudah tersimpan" }); if (cur.date&&cur.date!==today) await setJson("price-snapshot-prev",cur); const prices={}; items.forEach(({barcode,price})=>{if(barcode)prices[barcode]=Number(price)||0;}); await setJson("price-snapshot-current",{date:today,prices}); return json({ success: true, saved: Object.keys(prices).length }); }
    if (path === "/product-request" && method === "POST") { const { barcode, namaBarang, keterangan, username } = body; if (!barcode||!namaBarang||!username) return json({ success: false, message: "barcode, namaBarang, username wajib" }, 400); const list = await getJson("product-requests",[]); list.unshift({ id: crypto.randomUUID(), barcode: barcode.trim(), namaBarang: namaBarang.trim(), keterangan: (keterangan??"").trim(), username: username.trim(), createdAt: new Date().toISOString(), resolved: false }); if (list.length>500) list.length=500; await setJson("product-requests",list); return json({ success: true }); }
    if (path === "/product-request" && method === "GET") { if (q.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); let list = await getJson("product-requests",[]); if (q.showResolved!=="1") list=list.filter(r=>!r.resolved); return json({ success: true, requests: list }); }
    const prMatch = path.match(/^\/product-request\/([^/]+)\/resolve$/);
    if (prMatch && method === "PATCH") { if (body.adminPassword !== ADMIN_PASSWORD) return json({ success: false, message: "Unauthorized" }, 403); const list = await getJson("product-requests",[]); const idx = list.findIndex(r=>r.id===prMatch[1]); if (idx===-1) return json({ success: false, message: "Tidak ditemukan" }, 404); list[idx].resolved=true; list[idx].resolvedAt=new Date().toISOString(); await setJson("product-requests",list); return json({ success: true }); }
    return json({ error: "Not found" }, 404);
  } catch(err) { return json({ error: "Internal server error", detail: String(err) }, 500); }
}